#!/usr/bin/env perl

# References:
#   man urxvtperl
#   http://jbl.web.cern.ch/jbl/doc/urxvt/

# On .Xdefaults add:
#   urxvt.perl-ext: notifyme

sub on_start {
    my ($self) = @_;
    ()
}

sub on_bell {
    my ($self) = @_;
    unless ( $self->focus ) {
        $self->exec_async("/usr/bin/notify-send",
                          "--expire-time=10000",
                          "--icon=". $ENV{"HOME"} ."/.icons/cortana.png",
                          "SENPAI!",
                          "Notice me!"
                      );
    }
}
