#!/usr/bin/env perl
#use Data::Dumper;

# References:
#   man urxvtperl
#   http://jbl.web.cern.ch/jbl/doc/urxvt/

# On .Xdefaults add:
#   urxvt.perl-ext: notifyme

sub on_start {
    my ($self) = @_;
    $self->{show_alert} = 0;
    warn $self->vt;
    warn $self->parent;
    ()
}

sub on_user_command {
    my ($self, $action) = @_;
    if ($action eq "notifyme:activate") {
       $self->{show_alert} = 1; 
    }
    ()
}

sub on_bell {
    my ($self) = @_;
    warn "you whin";
    if ( $self->{show_alert} ) {
        $self->exec_async("/usr/bin/notify-send",
                          "--expire-time=10000",
                          "--icon=". $ENV{"HOME"} ."/.icons/cortana.png",
                          "SENPAI!",
                          "Notice me!"
                      );
        $self->{show_alert} = 0;
    }
}
