#!/usr/bin/env perl

# References:
#   man urxvtperl
#   http://jbl.web.cern.ch/jbl/doc/urxvt/

# On .Xdefaults add:
#   urxvt.perl-ext: notifyme

sub on_start {
    my ($self) = @_;
    $self->{show_alert} = 0;
    ()
}

sub on_user_command {
    my ($self, $action) = @_;
    if ($action eq "notifyme:activate") {
       $self->{show_alert} = 1; 
    }
    ()
}

sub on_bell {
    my ($self) = @_;
    warn "you whin";
    if ( $self->{show_alert} ) {
        $self->exec_async("/usr/bin/notify-send","title","message");
        $self->{show_alert} = 0;
    }
}
